### PR TITLE
force disable Lift2Wake

### PR DESCRIPTION
**Pull request by anomalchik**

### CODE REVIEW

**Comment by Quarx2k** [comment]
Interesting, but where this config in https://github.com/CyanogenMod/android_packages_apps_Settings/blob/cm-12.1/res/values/bools.xml ?

**Comment by anomalchik** [comment]
Sorry. I think these changes will be in 12.1 but on only cm 12.0 http://review.cyanogenmod.org/#/c/92297/

**Comment by nikich340** [comment]
Working in blisspop-5.1.1. Но может проще писать по-русски?

**Comment by nikich340** [comment]
Lil. Why do you remember about this now?

**Pull request closed without merging**
